### ISSUE TITLE
Can't get ispindel to work as beer temp sensor.

### ISSUE THREAD

**Issue by tblok** [vitotai/BrewPiLess#93]
It seems as I can't get the ispindel to work as the beer sensor for temperature.

I am getting the values as aux temp ok, also tilt and battery shows ok so there is nothing wrong with my ispindel.
Also in the device setup i set the external sensor to beer temp, but it never gets any value but 0.

I have tried the  default image for 3.0rc4 and also 2.4, 2.5(final) all with the same result,

**Comment by tblok** [comment]
Cool :) I will try this after i finish my latest brew on 2.5

**Comment by solbero** [comment]
It doesn't seem like this issue is fixed in v3.0. All the data from the iSpindel displays correctly in Brewpiless, except for the temp readings. The readings are displayed correctly on the iSpindel info page, but it seems like they are not read by Brewpiless.

**Comment by kynsi** [comment]
This is still an issue. Having the same problems with the latest release (4.1).
